language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '8'
before_script:
  - npm prune
after_success:
  - npm run report-coverage
  - npm run semantic-release
